# Generated by Django 3.2.2 on 2021-05-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210517_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='questions',
            field=models.ManyToManyField(to='myapi.Question'),
        ),
    ]
