# Generated by Django 3.2.2 on 2021-05-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_user_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='completed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
