# Generated by Django 3.2.2 on 2021-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20210723_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='score',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tasksInst',
            field=models.ManyToManyField(to='myapi.Tasks'),
        ),
    ]
