# Generated by Django 3.2.2 on 2021-07-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_rename_number_tasks_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='centerService',
            field=models.CharField(default='CESE', max_length=60),
            preserve_default=False,
        ),
    ]
