# Generated by Django 3.2.2 on 2021-07-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_user_centerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='centerService',
            field=models.CharField(default='general', max_length=60),
            preserve_default=False,
        ),
    ]
