# Generated by Django 3.2.2 on 2021-07-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_tasks_centerservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completed',
        ),
    ]
